name: Front End Workflow
on:
  push:
    branches: main
jobs:
  deploy:
    name: Upload to S3 bucket
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Check out repo onto runner
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::565173394051:role/github_actions_role
          aws-region: us-east-1
          
      - name: Terraform Init
        run: terraform init -input=false
        
      - name: Terraform Plan
        run: terraform plan -destroy -out=destroy.tfplan -input=false
      
#      - name: Copy files to the website with the AWS CLI
#        run: |
#          aws s3 sync assets/ s3://cs-resume-dev
